Repository OpenAEV-Platform/openaev, pull requests merged in 2024-06, with the labels that each got.

#1001 [backend] add index
  openbas-api/src/main/java/io/openbas/migration/V3_19__Add_index_for_atomic_testings.java
Labels: filigran team

#1015 [backend/frontend] add policies page
  openbas-api/src/main/java/io/openbas/rest/settings/PlatformSettingsApi.java
  openbas-api/src/main/java/io/openbas/rest/settings/form/PolicyInput.java
  openbas-api/src/main/java/io/openbas/rest/settings/response/PlatformSetting.java
  openbas-api/src/main/java/io/openbas/rest/settings/response/PlatformSettings.java
  openbas-api/src/main/java/io/openbas/service/PlatformSettingsService.java
  openbas-front/src/actions/Application.js
  openbas-front/src/actions/Schema.js
  openbas-front/src/actions/helper.d.ts
  openbas-front/src/admin/components/common/articles/ArticleForm.js
  openbas-front/src/admin/components/components/challenges/ChallengeForm.js
  openbas-front/src/admin/components/settings/Index.tsx
  openbas-front/src/admin/components/settings/SecurityMenu.tsx
  openbas-front/src/admin/components/settings/policies/Policies.tsx
  openbas-front/src/admin/components/settings/policies/PolicyForm.tsx
  openbas-front/src/components/fields/MarkDownField.tsx
  openbas-front/src/components/fields/OldMarkDownField.tsx
  openbas-front/src/public/components/login/Login.js
  openbas-front/src/utils/Localization.js
  openbas-front/src/utils/api-types.d.ts
  openbas-model/src/main/java/io/openbas/database/model/Setting.java
  openbas-model/src/main/java/io/openbas/database/model/SettingKeys.java
Labels: filigran team

#1048 [backend] Change external reference resolution for OpenCTI integration
  openbas-api/src/main/java/io/openbas/opencti/OpenCTIApi.java
  openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioApi.java
  openbas-api/src/main/java/io/openbas/service/ScenarioService.java
  openbas-api/src/main/java/io/openbas/utils/ResultUtils.java
  openbas-model/src/main/java/io/openbas/database/repository/ScenarioRepository.java
Labels: filigran team

#1049 [frontend] fix channels filter in definition
  openbas-front/src/admin/components/common/articles/Articles.tsx
  openbas-front/src/admin/components/components/channels/ChannelsFilter.tsx
Labels: filigran team

#1054 [backend/frontend] Fix reply to function in animation>mail section
  openbas-api/src/main/java/io/openbas/config/GlobalExceptionHandler.java
  openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java
  openbas-api/src/main/java/io/openbas/rest/inject/form/DirectInjectInput.java
  openbas-front/src/admin/components/simulations/simulation/mails/Communication.js
  openbas-front/src/admin/components/simulations/simulation/mails/Inject.js
Labels: filigran team

#1050 Imported scenario keeps the status / scheduling
  openbas-api/src/main/java/io/openbas/collectors/expectations_expiration_manager/service/ExpectationsExpirationManagerService.java
  openbas-api/src/main/java/io/openbas/config/AppConfig.java
  openbas-api/src/main/java/io/openbas/helper/ObjectMapperHelper.java
  openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java
  openbas-api/src/main/java/io/openbas/rest/scenario/export/ScenarioExportMixins.java
  openbas-api/src/main/java/io/openbas/rest/scenario/export/ScenarioFileExport.java
  openbas-api/src/main/java/io/openbas/rest/scenario/form/ScenarioRecurrenceInput.java
  openbas-api/src/main/java/io/openbas/service/ScenarioService.java
Labels: filigran team

#1066 [backend] Improv performance on challenges
  openbas-api/src/main/java/io/openbas/rest/challenge/ChallengeApi.java
  openbas-api/src/main/java/io/openbas/rest/challenge/ChallengeHelper.java
  openbas-api/src/main/java/io/openbas/rest/challenge/ExerciseChallengeApi.java
  openbas-api/src/main/java/io/openbas/rest/challenge/ScenarioChallengeApi.java
  openbas-api/src/main/java/io/openbas/rest/challenge/output/ChallengeOutput.java
  openbas-model/src/main/java/io/openbas/database/model/Challenge.java
  openbas-model/src/main/java/io/openbas/database/model/ChallengeFlag.java
  openbas-model/src/main/java/io/openbas/database/specification/InjectSpecification.java
Labels: filigran team

#1051 [frontend] Refact timeline composant
  openbas-front/src/actions/atomic_testings/atomic-testing-helper.d.ts
  openbas-front/src/actions/injects/inject-helper.d.ts
  openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingPopover.tsx
  openbas-front/src/admin/components/common/injects/InjectIcon.js
  openbas-front/src/admin/components/simulations/simulation/Index.tsx
  openbas-front/src/admin/components/simulations/simulation/timeline/Timeline.js
  openbas-front/src/admin/components/simulations/simulation/timeline/TimelineOverview.tsx
  openbas-front/src/components/Timeline.tsx
Labels: filigran team

#1059 [backend] Fix on get exercise details to have better performance
  openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java
  openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseDetails.java
  openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseSimple.java
  openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseUpdateStatusInput.java
  openbas-api/src/main/java/io/openbas/rest/helper/TeamHelper.java
  openbas-api/src/main/java/io/openbas/scheduler/jobs/InjectsExecutionJob.java
  openbas-api/src/test/java/io/openbas/helper/InjectHelperTest.java
  openbas-api/src/test/java/io/openbas/service/ExerciseExpectationServiceTest.java
  openbas-model/src/main/java/io/openbas/database/model/Exercise.java
  openbas-model/src/main/java/io/openbas/database/model/ExerciseStatus.java
  openbas-model/src/main/java/io/openbas/database/model/ExerciseTeamUser.java
  openbas-model/src/main/java/io/openbas/database/model/Inject.java
  openbas-model/src/main/java/io/openbas/database/raw/RawEvaluation.java
  openbas-model/src/main/java/io/openbas/database/raw/RawExercise.java
  openbas-model/src/main/java/io/openbas/database/raw/RawGrant.java
  openbas-model/src/main/java/io/openbas/database/raw/RawInject.java
  openbas-model/src/main/java/io/openbas/database/raw/RawObjective.java
  openbas-model/src/main/java/io/openbas/database/raw/RawPause.java
  openbas-model/src/main/java/io/openbas/database/repository/EvaluationRepository.java
  openbas-model/src/main/java/io/openbas/database/repository/ExerciseRepository.java
  openbas-model/src/main/java/io/openbas/database/repository/ExerciseTeamUserRepository.java
  openbas-model/src/main/java/io/openbas/database/repository/GrantRepository.java
  openbas-model/src/main/java/io/openbas/database/repository/InjectRepository.java
  openbas-model/src/main/java/io/openbas/database/repository/ObjectiveRepository.java
  openbas-model/src/main/java/io/openbas/database/repository/PauseRepository.java
  openbas-model/src/main/java/io/openbas/database/specification/ExerciseSpecification.java
  openbas-model/src/main/java/io/openbas/database/specification/InjectSpecification.java
Labels: filigran team

#1061 [backend/frontend] Improv injects perf
  openbas-api/src/main/java/io/openbas/rest/atomic_testing/AtomicTestingApi.java
  openbas-api/src/main/java/io/openbas/rest/inject/ExerciseInjectApi.java
  openbas-api/src/main/java/io/openbas/rest/inject/InjectApi.java
  openbas-api/src/main/java/io/openbas/rest/inject/ScenarioInjectApi.java
  openbas-api/src/main/java/io/openbas/rest/inject/output/InjectOutput.java
  openbas-api/src/main/java/io/openbas/service/InjectService.java
  openbas-framework/src/main/java/io/openbas/utils/JpaUtils.java
  openbas-front/src/actions/Inject.js
  openbas-front/src/actions/atomic_testings/atomic-testing-actions.ts
  openbas-front/src/actions/injects/inject-action.ts
  openbas-front/src/actions/injects/inject-helper.d.ts
  openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingPopover.tsx
  openbas-front/src/admin/components/common/Context.ts
  openbas-front/src/admin/components/common/injects/InjectDefinition.js
  openbas-front/src/admin/components/common/injects/InjectPopover.tsx
  openbas-front/src/admin/components/common/injects/Injects.js
  openbas-front/src/admin/components/common/injects/UpdateInject.tsx
  openbas-front/src/admin/components/scenarios/scenario/ScenarioContext.ts
  openbas-front/src/admin/components/scenarios/scenario/injects/ScenarioInjects.tsx
  openbas-front/src/admin/components/simulations/simulation/ExerciseContext.ts
  openbas-front/src/admin/components/simulations/simulation/injects/ExerciseInjects.tsx
  openbas-front/src/admin/components/simulations/simulation/mails/Mails.js
  openbas-front/src/admin/components/simulations/simulation/timeline/TimelineOverview.tsx
  openbas-front/src/public/components/login/Login.js
  openbas-front/src/utils/ArrayUtils.ts
  openbas-front/src/utils/api-types.d.ts
  openbas-model/src/main/java/io/openbas/database/model/Inject.java
  openbas-model/src/main/java/io/openbas/database/raw/RawInject.java
  openbas-model/src/main/java/io/openbas/database/repository/InjectRepository.java
  openbas-model/src/main/java/io/openbas/helper/InjectModelHelper.java
Labels: filigran team

#1062 [Frontend]Improve select date widgets
  openbas-front/src/admin/components/scenarios/scenario/Index.tsx
  openbas-front/src/admin/components/scenarios/scenario/ScenarioHeader.tsx
  openbas-front/src/admin/components/scenarios/scenario/ScenarioRecurringFormDialog.tsx
  openbas-front/src/admin/components/simulations/simulation/ExerciseDateForm.js
  openbas-front/src/admin/components/simulations/simulation/ExerciseDateForm.tsx
  openbas-front/src/admin/components/simulations/simulation/ExerciseDatePopover.tsx
  openbas-front/src/utils/Localization.js
Labels: filigran team

#1079 Issue/877 final improvements
  openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java
  openbas-api/src/main/java/io/openbas/rest/helper/TeamHelper.java
  openbas-api/src/main/java/io/openbas/rest/inject/output/InjectOutput.java
  openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioApi.java
  openbas-api/src/main/java/io/openbas/rest/team/TeamApi.java
  openbas-front/src/actions/Schema.js
  openbas-front/src/actions/injects/Inject.d.ts
  openbas-front/src/actions/injects/inject-helper.d.ts
  openbas-front/src/admin/components/common/articles/Articles.tsx
  openbas-front/src/admin/components/common/injects/InjectIcon.js
  openbas-front/src/admin/components/common/injects/Injects.js
  openbas-front/src/admin/components/scenarios/scenario/articles/ScenarioArticles.tsx
  openbas-front/src/admin/components/simulations/simulation/ExerciseDatePopover.tsx
  openbas-front/src/admin/components/simulations/simulation/injects/ExerciseInjects.tsx
  openbas-front/src/admin/components/simulations/simulation/timeline/TimelineOverview.tsx
  openbas-front/src/components/Timeline.tsx
  openbas-front/src/utils/Localization.js
  openbas-front/src/utils/api-types.d.ts
  openbas-model/src/main/java/io/openbas/database/repository/InjectRepository.java
Labels: filigran team

#1085 [backend] Fixing random login errors
  openbas-api/src/main/java/io/openbas/config/OpenBASSaml2AuthenticationRequestRepository.java
Labels: filigran team

#1090 [backend/frontend] Add pagination in exercise list and improv performance
  openbas-api/src/main/java/io/openbas/rest/atomic_testing/form/AtomicTestingDetailOutput.java
  openbas-api/src/main/java/io/openbas/rest/challenge/ExerciseChallengeApi.java
  openbas-api/src/main/java/io/openbas/rest/challenge/ScenarioChallengeApi.java
  openbas-api/src/main/java/io/openbas/rest/channel/ExerciseArticleApi.java
  openbas-api/src/main/java/io/openbas/rest/channel/ScenarioArticleApi.java
  openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java
  openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseService.java
  openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseSimple.java
  openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioApi.java
  openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioExerciseApi.java
  openbas-api/src/main/java/io/openbas/service/InjectService.java
  openbas-api/src/main/java/io/openbas/utils/pagination/SortUtilsCriteriaBuilder.java
  openbas-framework/src/main/java/io/openbas/utils/JpaUtils.java
  openbas-front/src/actions/scenarios/scenario-actions.ts
  openbas-front/src/admin/components/Dashboard.tsx
  openbas-front/src/admin/components/scenarios/scenario/Scenario.tsx
  openbas-front/src/admin/components/simulations/ExerciseList.tsx
  openbas-front/src/admin/components/simulations/Exercises.tsx
  openbas-front/src/utils/Localization.js
  openbas-model/src/main/java/io/openbas/database/criteria/ExerciseCriteria.java
  openbas-model/src/main/java/io/openbas/database/model/Exercise.java
  openbas-model/src/main/java/io/openbas/database/raw/RawInject.java
  openbas-model/src/main/java/io/openbas/database/specification/ExerciseSpecification.java
Labels: filigran team

#1114 Update test-feature-branch workflow to use new AWX endpoint
  .github/workflows/test-feature-branch.yml
Labels: filigran team

#1108 [backend] fix accumulation score of expectations
  openbas-model/src/main/java/io/openbas/database/audit/BaseEvent.java
Labels: bug, filigran team

#1136 [backend] filter data null
  openbas-model/src/main/java/io/openbas/database/converter/ContentConverter.java
Labels: filigran team

#1133 [backend] Make the admin property filterable
  openbas-model/src/main/java/io/openbas/database/model/User.java
Labels: filigran team

#1144 [backend] fix null pointer exc
  openbas-api/src/main/java/io/openbas/service/InjectService.java
  openbas-model/src/main/java/io/openbas/database/model/Inject.java
Labels: technical improvement, filigran team

#1082 Issue/950 inject broken filter for the attck matrix
  openbas-api/src/main/java/io/openbas/rest/injector_contract/InjectorContractApi.java
  openbas-api/src/test/java/io/openbas/injects/InjectCrudTest.java
  openbas-api/src/test/java/io/openbas/rest/ChallengeApiTest.java
  openbas-api/src/test/java/io/openbas/rest/UserApiTest.java
  openbas-api/src/test/java/io/openbas/scenario/ScenarioToExerciseServiceTest.java
  openbas-api/src/test/java/io/openbas/service/ExerciseExpectationServiceTest.java
  openbas-api/src/test/java/io/openbas/utils/fixtures/UserFixture.java
  openbas-front/src/actions/InjectorContracts.js
  openbas-front/src/actions/Schema.js
  openbas-front/src/admin/components/common/filters/MitreFilter.tsx
  openbas-front/src/utils/api-types.d.ts
  openbas-model/src/main/java/io/openbas/database/model/InjectorContract.java
  openbas-model/src/main/java/io/openbas/database/raw/RawInjectorsContrats.java
  openbas-model/src/main/java/io/openbas/database/repository/InjectorContractRepository.java
Labels: filigran team

#1146 [backend] fix export tags in scenarios and show expectations
  openbas-api/src/main/java/io/openbas/rest/inject/output/InjectOutput.java
  openbas-api/src/main/java/io/openbas/rest/scenario/export/ScenarioExportMixins.java
  openbas-front/src/admin/components/common/injects/InjectIcon.js
Labels: bug, filigran team

#1152 [frontend] Move scenarios with simulations and AT in the menu
  openbas-front/src/admin/components/nav/LeftBar.tsx
Labels: filigran team

#1153 [backend/frontend] Sort simulation by updated date
  openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseService.java
  openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseSimple.java
  openbas-front/src/admin/components/atomic_testings/InjectList.tsx
  openbas-front/src/admin/components/scenarios/Scenarios.tsx
  openbas-front/src/admin/components/simulations/ExerciseList.tsx
  openbas-front/src/admin/components/simulations/Exercises.tsx
  openbas-front/src/utils/api-types.d.ts
Labels: filigran team

#1149 [frontend] Fix on layout of the image no working
  openbas-front/src/admin/components/common/injects/CreateInject.tsx
  openbas-front/src/admin/components/common/injects/UpdateInject.tsx
  openbas-front/src/components/common/Drawer.tsx
Labels: filigran team

#1116 [backend] Fix recurring scenario not cleaned
  openbas-api/src/main/java/io/openbas/scheduler/jobs/ScenarioExecutionJob.java
  openbas-api/src/main/java/io/openbas/service/ScenarioService.java
  openbas-api/src/test/java/io/openbas/scheduler/jobs/ScenarioExecutionJobTest.java
  openbas-model/src/main/java/io/openbas/database/specification/ScenarioSpecification.java
Labels: filigran team

#1115 [Frontend]Scenario scores display
  openbas-front/src/admin/components/scenarios/scenario/ScenarioDistributionByExercise.tsx
  openbas-front/src/utils/Charts.js
Labels: filigran team

#1084 [backend] Improv performance on atomic testing pagination list
  openbas-api/src/main/java/io/openbas/rest/atomic_testing/AtomicTestingApi.java
  openbas-api/src/main/java/io/openbas/rest/inject/output/AtomicTestingOutput.java
  openbas-api/src/main/java/io/openbas/rest/inject/output/InjectOutput.java
  openbas-api/src/main/java/io/openbas/service/AtomicTestingService.java
  openbas-api/src/main/java/io/openbas/service/InjectService.java
  openbas-api/src/main/java/io/openbas/utils/AtomicTestingUtils.java
  openbas-framework/src/main/java/io/openbas/utils/JpaUtils.java
  openbas-model/src/main/java/io/openbas/database/criteria/InjectCriteria.java
  openbas-model/src/main/java/io/openbas/database/model/Inject.java
  openbas-model/src/main/java/io/openbas/database/raw/RawAsset.java
  openbas-model/src/main/java/io/openbas/database/raw/RawTeam.java
  openbas-model/src/main/java/io/openbas/database/repository/InjectExpectationRepository.java
  openbas-model/src/main/java/io/openbas/helper/InjectModelHelper.java
Labels: filigran team

#1148 When editing an endpoint without description, form cannot be validated
  openbas-front/src/admin/components/assets/endpoints/EndpointPopover.tsx
Labels: filigran team

#1156 [backend] Validate contracts undefined, null or empty (#1121)
  openbas-front/src/admin/components/common/injects/CreateInject.tsx
Labels: filigran team

#1160 [frontend] fix crash page atomic testing after deleting a payload
  openbas-front/src/actions/Schema.js
  openbas-front/src/admin/components/atomic_testings/InjectList.tsx
  openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTesting.tsx
  openbas-front/src/admin/components/atomic_testings/atomic_testing/AtomicTestingDetail.tsx
Labels: filigran team

#1155 [frontend] Fix options for tone in message (#1126)
  openbas-front/src/admin/components/common/form/TextFieldAskAI.tsx
Labels: filigran team
