Repository OpenAEV-Platform/openaev, pull requests merged in 2024-02, with the labels that each got.

#572 [backend] Add ignore case for findByEmail and add int tests
  openex-api/src/main/java/io/openex/config/AppSecurityConfig.java
  openex-api/src/main/java/io/openex/injects/email/service/ImapService.java
  openex-api/src/main/java/io/openex/migration/V2_72__Add_index_user_email_lower_case.java
  openex-api/src/main/java/io/openex/rest/user/UserApi.java
  openex-api/src/main/java/io/openex/rest/user/form/login/LoginUserInput.java
  openex-api/src/test/java/io/openex/IntegrationTest.java
  openex-api/src/test/java/io/openex/rest/AssetGroupApiTest.java
  openex-api/src/test/java/io/openex/rest/EndpointApiTest.java
  openex-api/src/test/java/io/openex/rest/UserApiTest.java
  openex-api/src/test/java/io/openex/rest/utils/WithMockObserverUserSecurityContextFactory.java
  openex-api/src/test/java/io/openex/rest/utils/WithMockPlannerUserSecurityContextFactory.java
  openex-api/src/test/java/io/openex/rest/utils/fixtures/UserFixture.java
  openex-model/src/main/java/io/openex/database/repository/UserRepository.java
Labels: bug

#574 [frontend] use a FormTextHelper to fix style of text editor when requ…
  openex-front/src/components/EnrichedTextField.js
Labels: filigran team

#575 [frontend] adding check on landline phone in player form (#515)
  openex-api/src/main/java/io/openex/rest/user/form/player/UpdatePlayerInput.java
  openex-api/src/main/java/io/openex/rest/user/form/user/UpdateUserInput.java
  openex-front/src/admin/components/profile/ProfileForm.js
  openex-front/src/admin/components/settings/users/UserForm.js
  openex-front/src/admin/components/teams/players/PlayerForm.tsx
  openex-front/src/utils/Localization.js
Labels: filigran team

#615 [frontend] fix vite hmr on .js files (#614)
  openex-front/vite.config.ts
Labels: filigran team

#606 Openex featurebranch actions
  .github/workflows/test-feature-branch.yml
  Dockerfile_ga
Labels: build
